CREATE OR REPLACE PROCEDURE HELLO_WORLD (
    NUM_ENTRIES NUMBER,
    NAME_ARRAY OWA.VC_ARR,
    VALUE_ARRAY OWA.VC_ARR,
    RESERVED OWA.VC_ARR
) IS
BEGIN
    HTP.PRINT('Hello World');
    DBMS_OUTPUT.PUT_LINE('Test DBMS_OUTPUT');
END;