CREATE OR REPLACE PROCEDURE HTTP_PARAM (
    NUM_ENTRIES NUMBER,
    NAME_ARRAY OWA.VC_ARR,
    VALUE_ARRAY OWA.VC_ARR,
    RESERVED OWA.VC_ARR
) IS
BEGIN
    HTP.PRINT('P1 => ' || GET_PARAM(NUM_ENTRIES, NAME_ARRAY, VALUE_ARRAY, 'P1'));
    HTP.PRINT('P2 => ' || GET_PARAM(NUM_ENTRIES, NAME_ARRAY, VALUE_ARRAY, 'P2'));
END;