CREATE OR REPLACE PROCEDURE SET_COOKIE (
    NUM_ENTRIES NUMBER,
    NAME_ARRAY OWA.VC_ARR,
    VALUE_ARRAY OWA.VC_ARR,
    RESERVED OWA.VC_ARR
) IS
    V_COOKIE OWA_COOKIE.COOKIE;
BEGIN
    V_COOKIE := OWA_COOKIE.GET('MODPLSQL_SESSION');

    HTP.PRINT('COOKIE => ' || V_COOKIE.vals(1));
END;