CREATE OR REPLACE PROCEDURE GET_COOKIE (
    NUM_ENTRIES NUMBER,
    NAME_ARRAY OWA.VC_ARR,
    VALUE_ARRAY OWA.VC_ARR,
    RESERVED OWA.VC_ARR
) IS
BEGIN
    OWA_COOKIE.SEND('MODPLSQL_SESSION', 'HASH_COOKIE');
END;